#!/usr/bin/bash

echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo 
echo 50 > /sys/devices/system/cpu/intel_pstate/max_perf_pct 
echo 50 > /sys/devices/system/cpu/intel_pstate/min_perf_pct

for cpu in $(seq 0 7); do sudo cpufreq-set -c $cpu -g performance; done
