#!/bin/bash

function disable_core {
	for i in $(seq $1 $2); do 
		echo 0 > /sys/devices/system/cpu/cpu${i}/online
	done
}

function enable_core {
	for i in $(seq $1 $2); do 
		echo 1 > /sys/devices/system/cpu/cpu${i}/online
	done
}

echo 1 > /proc/sys/kernel/sched_dl_fallback_to_gedf

#################################################
# Test with varying utilization
#################################################

function __utilization_test {
	for u in $(seq $2 0.1 $3 | sed 's/,/./'); do
		./apedf-scripts/imp_test -c $1 -u ${u} -e 510 ### Edit test number
	done
}

function utilization_test {
	echo 0 > /proc/sys/kernel/sched_dl_policy
	__utilization_test $1 $2 $3

	echo 1 > /proc/sys/kernel/sched_dl_policy
	echo 0 > /proc/sys/kernel/sched_dl_xf_pull
	__utilization_test $1 $2 $3
	
	echo 1 > /proc/sys/kernel/sched_dl_xf_pull
	__utilization_test $1 $2 $3
}

disable_core 2 3
500_test 2 1.4 1.9


enable_core 2 3
500_test 4 2.4 3.8

#enable_core 4 7
#500_test 8 4.4 7.6

exit 0

#################################################
# 501
#################################################

function 501_502_test {
	echo 0 > /proc/sys/kernel/sched_dl_policy
	./apedf-scripts/imp_test -t $1 -e $2

	echo 1 > /proc/sys/kernel/sched_dl_policy
	echo 0 > /proc/sys/kernel/sched_dl_xf_pull
	./apedf-scripts/imp_test -t $1 -e $2
	
	echo 1 > /proc/sys/kernel/sched_dl_xf_pull
	./apedf-scripts/imp_test -t $1 -e $2
}

for t in $(seq 15 25); do
	501_502_test ${t} 501
done

#################################################
# 502
#################################################

disable_core 4 7
for t in $(seq 7 15); do
	501_502_test ${t} 502
done

#################################################
# 503
#################################################
function 503_test {
	echo 0 > /proc/sys/kernel/sched_dl_policy
	./apedf-scripts/imp_test -c $1 -u $(echo "$1 * 0.8" | bc) -e 503

	echo 1 > /proc/sys/kernel/sched_dl_policy
	echo 0 > /proc/sys/kernel/sched_dl_xf_pull
	./apedf-scripts/imp_test -c $1 -u $(echo "$1 * 0.8" | bc) -e 503
	
	echo 1 > /proc/sys/kernel/sched_dl_xf_pull
	./apedf-scripts/imp_test -c $1 -u $(echo "$1 * 0.8" | bc) -e 503
}

disable_core 2 40
503_test 2

enable_core 2 3
503_test 4

enable_core 4 7
503_test 8
